object Versions {
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.1"
    const val composeCompiler = "1.4.6"
    const val hilt = "2.51.1"
    const val hiltNavigationCompose = "1.2.0"
    const val okHttp = "5.0.0-alpha.2"
    const val room = "2.6.1"
    const val kotlinXSerialization = "1.6.3"
    const val retrofit2KotlinxSerializationConverter = "0.8.0"
    const val converterGson = "2.11.0"
    const val retrofit = "2.11.0"
    const val composeNav = "2.8.2"
    const val timber = "5.0.1"
    const val dataStorePrefs = "1.1.1"
    const val workRuntimeKtx = "2.10.0"
    const val initilizer = "1.2.0-alpha02"
    const val reordable = "0.9.6"
}