lint:
  name: Code Linting
  runs-on: ubuntu-latest
  needs: validate
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Create keys.properties
      run: |
        echo "PROD_BACKEND_URL=${{ secrets.PROD_BACKEND_URL }}" > keys.properties
        echo "DEV_BACKEND_URL=${{ secrets.DEV_BACKEND_URL }}" >> keys.properties
        echo "STAGING_BACKEND_URL=${{ secrets.STAGING_BACKEND_URL }}" >> keys.properties
        echo "RELEASE_STORE_FILE=keystore.jks" >> keys.properties
        echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keys.properties
        echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> keys.properties
        echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keys.properties

    - name: Create keystore file
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

    - name: Run ktlint check
      run: ./gradlew ktlintCheck

    - name: Run Android Lint
      run: ./gradlew lintDebug

    - name: Upload lint reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lint-reports
        path: |
          **/build/reports/lint-results-*.html
          **/build/reports/ktlint/